<?php
/**
 * module-testcase:/unit/notice/menu.phtml
 *
 * @creation  2019-04-18
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-04-18
 */
namespace OP;

//	...
$root = ConvertURL('testcase:/') . 'unit/notice/';

?>
<section>
	|
	<a href="<?= $root ?>sendmail" >Sendmail</a>  |
</section>
