<?php
/**
 * unit-notice:/mail/notice.phtml
 *
 * @created   2016-11-30
 * @version   1.0
 * @package   unit-notice
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2016 (C) Tomoaki Nagahara All right reserved.
 */

 /** namespace
 *
 * @created   2019-03-17
 */
namespace OP;

//	...
if( false ){
	$notice = null;
}

//	Use functions.
include_once(__DIR__.'/notice.inc.php');

//	Timestamp
$timezone  = date_default_timezone_get();
$time_app  = Env::Timestamp();
$time_std  =   date(_OP_DATE_TIME_);
$time_gmt  = gmdate(_OP_DATE_TIME_);
$timestamp = $time_std;

//	GMT
if( $time_std !== $time_gmt ){
	$timestamp .= " {$timezone}";
	$timestamp .= " <i>(GMT: $time_gmt)</i>";
}

//	Frozen time
if( $time_std !== $time_app ){
	$timestamp .= ", <b>App: $time_app</b>";
}

//	Information of Visitor.
$ip			 = $_SERVER['REMOTE_ADDR']     ?? null;
$host		 = gethostbyaddr($ip);
$visitor	 = "$host ($ip)";
$ua			 = $_SERVER['HTTP_USER_AGENT'] ?? null;
$referer	 = $_SERVER['HTTP_REFERER']    ?? null;
$blacklist   = null;

//	Information of Server.
$scheme      = $_SERVER['REQUEST_SCHEME']  ?? '(empty)';
$host		 = $_SERVER['HTTP_HOST']       ?? null;
$url		 = $_SERVER['REQUEST_URI']     ?? null;
$url		 = $scheme .'://'. $host . $url;

//	If name resolve fail.
if( $ip === $host ){
	$blacklist = true;
	Load('Blacklist');
	Blacklist($blacklist);
}

//	...
if(!ob_start()){
	echo '<p>"ob_start" was failed. (Notice::Shutdown)</p>'.PHP_EOL;
	return false;
}

?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo $notice['message'] ?></title>
	<style type="text/css">
	body * {
		font-size: 9pt;
	}
	.bold {
		font-weight: bold;
	}
	.italic {
		font-style: italic;
	}
	</style>
</head>
<body>
	<div>
		<?php if( $messages = explode("\n", $notice['message']) ): ?>
			<?php for($i=0; $i<count($messages); $i++): ?>
				<?php if( $i === 0 ): ?>
					<p class="bold"><?= $messages[$i] ?></p>
				<?php elseif($messages[$i]): ?>
					<p class="italic"><?= $messages[$i] ?></p>
				<?php endif; ?>
			<?php endfor; ?>
		<?php endif; ?>
	</div>
	<table>
		<tr><th> Timestamp </th><td><?= $timestamp ?></td></tr>
		<tr><th> Visitor   </th><td><?= $visitor   ?></td></tr>
		<tr><th> UserAgent </th><td><?= $ua        ?></td></tr>
		<tr><th> URL       </th><td><?= $url       ?></td></tr>
		<tr><th> Referer   </th><td><?= $referer   ?></td></tr>
		<tr><th> Blacklist </th><td><?= $blacklist ?></td></tr>
	</table>
	<hr/>
	<?php _backtrace($notice['backtrace'] ?? []) ?>
</body>
</html>
<?php
//	...
return ob_get_clean();
